#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingFruitsWeb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HONAWEB")]
	public partial class FruitDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertADMIN(ADMIN instance);
    partial void UpdateADMIN(ADMIN instance);
    partial void DeleteADMIN(ADMIN instance);
    partial void InsertCHI_TIET_CHUYEN_HANG(CHI_TIET_CHUYEN_HANG instance);
    partial void UpdateCHI_TIET_CHUYEN_HANG(CHI_TIET_CHUYEN_HANG instance);
    partial void DeleteCHI_TIET_CHUYEN_HANG(CHI_TIET_CHUYEN_HANG instance);
    partial void InsertCHI_TIET_DON_HANG(CHI_TIET_DON_HANG instance);
    partial void UpdateCHI_TIET_DON_HANG(CHI_TIET_DON_HANG instance);
    partial void DeleteCHI_TIET_DON_HANG(CHI_TIET_DON_HANG instance);
    partial void InsertCHI_TIET_TRAI_CAY(CHI_TIET_TRAI_CAY instance);
    partial void UpdateCHI_TIET_TRAI_CAY(CHI_TIET_TRAI_CAY instance);
    partial void DeleteCHI_TIET_TRAI_CAY(CHI_TIET_TRAI_CAY instance);
    partial void InsertDON_HANG(DON_HANG instance);
    partial void UpdateDON_HANG(DON_HANG instance);
    partial void DeleteDON_HANG(DON_HANG instance);
    partial void InsertLOAI_TRAI_CAY(LOAI_TRAI_CAY instance);
    partial void UpdateLOAI_TRAI_CAY(LOAI_TRAI_CAY instance);
    partial void DeleteLOAI_TRAI_CAY(LOAI_TRAI_CAY instance);
    partial void InsertLOG_NHAP(LOG_NHAP instance);
    partial void UpdateLOG_NHAP(LOG_NHAP instance);
    partial void DeleteLOG_NHAP(LOG_NHAP instance);
    partial void InsertLOG_THANH_TOAN(LOG_THANH_TOAN instance);
    partial void UpdateLOG_THANH_TOAN(LOG_THANH_TOAN instance);
    partial void DeleteLOG_THANH_TOAN(LOG_THANH_TOAN instance);
    partial void InsertTRAI_CAY(TRAI_CAY instance);
    partial void UpdateTRAI_CAY(TRAI_CAY instance);
    partial void DeleteTRAI_CAY(TRAI_CAY instance);
    partial void InsertUSER(USER instance);
    partial void UpdateUSER(USER instance);
    partial void DeleteUSER(USER instance);
    #endregion
		
		public FruitDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HonaModel"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FruitDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FruitDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FruitDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FruitDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<CHI_TIET_CHUYEN_HANG> CHI_TIET_CHUYEN_HANGs
		{
			get
			{
				return this.GetTable<CHI_TIET_CHUYEN_HANG>();
			}
		}
		
		public System.Data.Linq.Table<CHI_TIET_DON_HANG> CHI_TIET_DON_HANGs
		{
			get
			{
				return this.GetTable<CHI_TIET_DON_HANG>();
			}
		}
		
		public System.Data.Linq.Table<CHI_TIET_TRAI_CAY> CHI_TIET_TRAI_CAYs
		{
			get
			{
				return this.GetTable<CHI_TIET_TRAI_CAY>();
			}
		}
		
		public System.Data.Linq.Table<DON_HANG> DON_HANGs
		{
			get
			{
				return this.GetTable<DON_HANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAI_TRAI_CAY> LOAI_TRAI_CAYs
		{
			get
			{
				return this.GetTable<LOAI_TRAI_CAY>();
			}
		}
		
		public System.Data.Linq.Table<LOG_NHAP> LOG_NHAPs
		{
			get
			{
				return this.GetTable<LOG_NHAP>();
			}
		}
		
		public System.Data.Linq.Table<LOG_THANH_TOAN> LOG_THANH_TOANs
		{
			get
			{
				return this.GetTable<LOG_THANH_TOAN>();
			}
		}
		
		public System.Data.Linq.Table<TRAI_CAY> TRAI_CAYs
		{
			get
			{
				return this.GetTable<TRAI_CAY>();
			}
		}
		
		public System.Data.Linq.Table<USER> USERs
		{
			get
			{
				return this.GetTable<USER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Auto_ID;
		
		private string _Ten_Dang_Nhap;
		
		private string _Mat_Khau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAuto_IDChanging(string value);
    partial void OnAuto_IDChanged();
    partial void OnTen_Dang_NhapChanging(string value);
    partial void OnTen_Dang_NhapChanged();
    partial void OnMat_KhauChanging(string value);
    partial void OnMat_KhauChanged();
    #endregion
		
		public ADMIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auto_ID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Auto_ID
		{
			get
			{
				return this._Auto_ID;
			}
			set
			{
				if ((this._Auto_ID != value))
				{
					this.OnAuto_IDChanging(value);
					this.SendPropertyChanging();
					this._Auto_ID = value;
					this.SendPropertyChanged("Auto_ID");
					this.OnAuto_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Dang_Nhap", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Ten_Dang_Nhap
		{
			get
			{
				return this._Ten_Dang_Nhap;
			}
			set
			{
				if ((this._Ten_Dang_Nhap != value))
				{
					this.OnTen_Dang_NhapChanging(value);
					this.SendPropertyChanging();
					this._Ten_Dang_Nhap = value;
					this.SendPropertyChanged("Ten_Dang_Nhap");
					this.OnTen_Dang_NhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mat_Khau", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Mat_Khau
		{
			get
			{
				return this._Mat_Khau;
			}
			set
			{
				if ((this._Mat_Khau != value))
				{
					this.OnMat_KhauChanging(value);
					this.SendPropertyChanging();
					this._Mat_Khau = value;
					this.SendPropertyChanged("Mat_Khau");
					this.OnMat_KhauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHI_TIET_CHUYEN_HANG")]
	public partial class CHI_TIET_CHUYEN_HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Chi_Tiet_CH;
		
		private string _Ho_Ten;
		
		private string _So_Dien_Thoai;
		
		private string _Dia_Chi_Nhan;
		
		private string _Ma_Don_Hang;
		
		private EntityRef<DON_HANG> _DON_HANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Chi_Tiet_CHChanging(string value);
    partial void OnMa_Chi_Tiet_CHChanged();
    partial void OnHo_TenChanging(string value);
    partial void OnHo_TenChanged();
    partial void OnSo_Dien_ThoaiChanging(string value);
    partial void OnSo_Dien_ThoaiChanged();
    partial void OnDia_Chi_NhanChanging(string value);
    partial void OnDia_Chi_NhanChanged();
    partial void OnMa_Don_HangChanging(string value);
    partial void OnMa_Don_HangChanged();
    #endregion
		
		public CHI_TIET_CHUYEN_HANG()
		{
			this._DON_HANG = default(EntityRef<DON_HANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Chi_Tiet_CH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Chi_Tiet_CH
		{
			get
			{
				return this._Ma_Chi_Tiet_CH;
			}
			set
			{
				if ((this._Ma_Chi_Tiet_CH != value))
				{
					this.OnMa_Chi_Tiet_CHChanging(value);
					this.SendPropertyChanging();
					this._Ma_Chi_Tiet_CH = value;
					this.SendPropertyChanged("Ma_Chi_Tiet_CH");
					this.OnMa_Chi_Tiet_CHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ho_Ten", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Ho_Ten
		{
			get
			{
				return this._Ho_Ten;
			}
			set
			{
				if ((this._Ho_Ten != value))
				{
					this.OnHo_TenChanging(value);
					this.SendPropertyChanging();
					this._Ho_Ten = value;
					this.SendPropertyChanged("Ho_Ten");
					this.OnHo_TenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Dien_Thoai", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string So_Dien_Thoai
		{
			get
			{
				return this._So_Dien_Thoai;
			}
			set
			{
				if ((this._So_Dien_Thoai != value))
				{
					this.OnSo_Dien_ThoaiChanging(value);
					this.SendPropertyChanging();
					this._So_Dien_Thoai = value;
					this.SendPropertyChanged("So_Dien_Thoai");
					this.OnSo_Dien_ThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dia_Chi_Nhan", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Dia_Chi_Nhan
		{
			get
			{
				return this._Dia_Chi_Nhan;
			}
			set
			{
				if ((this._Dia_Chi_Nhan != value))
				{
					this.OnDia_Chi_NhanChanging(value);
					this.SendPropertyChanging();
					this._Dia_Chi_Nhan = value;
					this.SendPropertyChanged("Dia_Chi_Nhan");
					this.OnDia_Chi_NhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Don_Hang", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Ma_Don_Hang
		{
			get
			{
				return this._Ma_Don_Hang;
			}
			set
			{
				if ((this._Ma_Don_Hang != value))
				{
					if (this._DON_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_Don_HangChanging(value);
					this.SendPropertyChanging();
					this._Ma_Don_Hang = value;
					this.SendPropertyChanged("Ma_Don_Hang");
					this.OnMa_Don_HangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DON_HANG_CHI_TIET_CHUYEN_HANG", Storage="_DON_HANG", ThisKey="Ma_Don_Hang", OtherKey="Ma_Don_Hang", IsForeignKey=true)]
		public DON_HANG DON_HANG
		{
			get
			{
				return this._DON_HANG.Entity;
			}
			set
			{
				DON_HANG previousValue = this._DON_HANG.Entity;
				if (((previousValue != value) 
							|| (this._DON_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DON_HANG.Entity = null;
						previousValue.CHI_TIET_CHUYEN_HANGs.Remove(this);
					}
					this._DON_HANG.Entity = value;
					if ((value != null))
					{
						value.CHI_TIET_CHUYEN_HANGs.Add(this);
						this._Ma_Don_Hang = value.Ma_Don_Hang;
					}
					else
					{
						this._Ma_Don_Hang = default(string);
					}
					this.SendPropertyChanged("DON_HANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHI_TIET_DON_HANG")]
	public partial class CHI_TIET_DON_HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Chi_Tiet_DH;
		
		private int _So_Luong_Xuat;
		
		private int _Don_Gia_Xuat;
		
		private string _Ma_Don_Hang;
		
		private string _Ma_Trai_Cay;
		
		private EntityRef<DON_HANG> _DON_HANG;
		
		private EntityRef<TRAI_CAY> _TRAI_CAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Chi_Tiet_DHChanging(string value);
    partial void OnMa_Chi_Tiet_DHChanged();
    partial void OnSo_Luong_XuatChanging(int value);
    partial void OnSo_Luong_XuatChanged();
    partial void OnDon_Gia_XuatChanging(int value);
    partial void OnDon_Gia_XuatChanged();
    partial void OnMa_Don_HangChanging(string value);
    partial void OnMa_Don_HangChanged();
    partial void OnMa_Trai_CayChanging(string value);
    partial void OnMa_Trai_CayChanged();
    #endregion
		
		public CHI_TIET_DON_HANG()
		{
			this._DON_HANG = default(EntityRef<DON_HANG>);
			this._TRAI_CAY = default(EntityRef<TRAI_CAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Chi_Tiet_DH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Chi_Tiet_DH
		{
			get
			{
				return this._Ma_Chi_Tiet_DH;
			}
			set
			{
				if ((this._Ma_Chi_Tiet_DH != value))
				{
					this.OnMa_Chi_Tiet_DHChanging(value);
					this.SendPropertyChanging();
					this._Ma_Chi_Tiet_DH = value;
					this.SendPropertyChanged("Ma_Chi_Tiet_DH");
					this.OnMa_Chi_Tiet_DHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Luong_Xuat", DbType="Int NOT NULL")]
		public int So_Luong_Xuat
		{
			get
			{
				return this._So_Luong_Xuat;
			}
			set
			{
				if ((this._So_Luong_Xuat != value))
				{
					this.OnSo_Luong_XuatChanging(value);
					this.SendPropertyChanging();
					this._So_Luong_Xuat = value;
					this.SendPropertyChanged("So_Luong_Xuat");
					this.OnSo_Luong_XuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Don_Gia_Xuat", DbType="Int NOT NULL")]
		public int Don_Gia_Xuat
		{
			get
			{
				return this._Don_Gia_Xuat;
			}
			set
			{
				if ((this._Don_Gia_Xuat != value))
				{
					this.OnDon_Gia_XuatChanging(value);
					this.SendPropertyChanging();
					this._Don_Gia_Xuat = value;
					this.SendPropertyChanged("Don_Gia_Xuat");
					this.OnDon_Gia_XuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Don_Hang", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Ma_Don_Hang
		{
			get
			{
				return this._Ma_Don_Hang;
			}
			set
			{
				if ((this._Ma_Don_Hang != value))
				{
					if (this._DON_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_Don_HangChanging(value);
					this.SendPropertyChanging();
					this._Ma_Don_Hang = value;
					this.SendPropertyChanged("Ma_Don_Hang");
					this.OnMa_Don_HangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Trai_Cay", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Ma_Trai_Cay
		{
			get
			{
				return this._Ma_Trai_Cay;
			}
			set
			{
				if ((this._Ma_Trai_Cay != value))
				{
					if (this._TRAI_CAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_Trai_CayChanging(value);
					this.SendPropertyChanging();
					this._Ma_Trai_Cay = value;
					this.SendPropertyChanged("Ma_Trai_Cay");
					this.OnMa_Trai_CayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DON_HANG_CHI_TIET_DON_HANG", Storage="_DON_HANG", ThisKey="Ma_Don_Hang", OtherKey="Ma_Don_Hang", IsForeignKey=true)]
		public DON_HANG DON_HANG
		{
			get
			{
				return this._DON_HANG.Entity;
			}
			set
			{
				DON_HANG previousValue = this._DON_HANG.Entity;
				if (((previousValue != value) 
							|| (this._DON_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DON_HANG.Entity = null;
						previousValue.CHI_TIET_DON_HANGs.Remove(this);
					}
					this._DON_HANG.Entity = value;
					if ((value != null))
					{
						value.CHI_TIET_DON_HANGs.Add(this);
						this._Ma_Don_Hang = value.Ma_Don_Hang;
					}
					else
					{
						this._Ma_Don_Hang = default(string);
					}
					this.SendPropertyChanged("DON_HANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAI_CAY_CHI_TIET_DON_HANG", Storage="_TRAI_CAY", ThisKey="Ma_Trai_Cay", OtherKey="Ma_Trai_Cay", IsForeignKey=true)]
		public TRAI_CAY TRAI_CAY
		{
			get
			{
				return this._TRAI_CAY.Entity;
			}
			set
			{
				TRAI_CAY previousValue = this._TRAI_CAY.Entity;
				if (((previousValue != value) 
							|| (this._TRAI_CAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRAI_CAY.Entity = null;
						previousValue.CHI_TIET_DON_HANGs.Remove(this);
					}
					this._TRAI_CAY.Entity = value;
					if ((value != null))
					{
						value.CHI_TIET_DON_HANGs.Add(this);
						this._Ma_Trai_Cay = value.Ma_Trai_Cay;
					}
					else
					{
						this._Ma_Trai_Cay = default(string);
					}
					this.SendPropertyChanged("TRAI_CAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHI_TIET_TRAI_CAY")]
	public partial class CHI_TIET_TRAI_CAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Chi_Tiet_TC;
		
		private string _Hinh_Trai_Cay;
		
		private string _Ma_Trai_Cay;
		
		private EntityRef<TRAI_CAY> _TRAI_CAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Chi_Tiet_TCChanging(string value);
    partial void OnMa_Chi_Tiet_TCChanged();
    partial void OnHinh_Trai_CayChanging(string value);
    partial void OnHinh_Trai_CayChanged();
    partial void OnMa_Trai_CayChanging(string value);
    partial void OnMa_Trai_CayChanged();
    #endregion
		
		public CHI_TIET_TRAI_CAY()
		{
			this._TRAI_CAY = default(EntityRef<TRAI_CAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Chi_Tiet_TC", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Chi_Tiet_TC
		{
			get
			{
				return this._Ma_Chi_Tiet_TC;
			}
			set
			{
				if ((this._Ma_Chi_Tiet_TC != value))
				{
					this.OnMa_Chi_Tiet_TCChanging(value);
					this.SendPropertyChanging();
					this._Ma_Chi_Tiet_TC = value;
					this.SendPropertyChanged("Ma_Chi_Tiet_TC");
					this.OnMa_Chi_Tiet_TCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh_Trai_Cay", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Hinh_Trai_Cay
		{
			get
			{
				return this._Hinh_Trai_Cay;
			}
			set
			{
				if ((this._Hinh_Trai_Cay != value))
				{
					this.OnHinh_Trai_CayChanging(value);
					this.SendPropertyChanging();
					this._Hinh_Trai_Cay = value;
					this.SendPropertyChanged("Hinh_Trai_Cay");
					this.OnHinh_Trai_CayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Trai_Cay", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Ma_Trai_Cay
		{
			get
			{
				return this._Ma_Trai_Cay;
			}
			set
			{
				if ((this._Ma_Trai_Cay != value))
				{
					if (this._TRAI_CAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_Trai_CayChanging(value);
					this.SendPropertyChanging();
					this._Ma_Trai_Cay = value;
					this.SendPropertyChanged("Ma_Trai_Cay");
					this.OnMa_Trai_CayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAI_CAY_CHI_TIET_TRAI_CAY", Storage="_TRAI_CAY", ThisKey="Ma_Trai_Cay", OtherKey="Ma_Trai_Cay", IsForeignKey=true)]
		public TRAI_CAY TRAI_CAY
		{
			get
			{
				return this._TRAI_CAY.Entity;
			}
			set
			{
				TRAI_CAY previousValue = this._TRAI_CAY.Entity;
				if (((previousValue != value) 
							|| (this._TRAI_CAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRAI_CAY.Entity = null;
						previousValue.CHI_TIET_TRAI_CAYs.Remove(this);
					}
					this._TRAI_CAY.Entity = value;
					if ((value != null))
					{
						value.CHI_TIET_TRAI_CAYs.Add(this);
						this._Ma_Trai_Cay = value.Ma_Trai_Cay;
					}
					else
					{
						this._Ma_Trai_Cay = default(string);
					}
					this.SendPropertyChanged("TRAI_CAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DON_HANG")]
	public partial class DON_HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Don_Hang;
		
		private string _Ma_Chi_Tiet_DH;
		
		private System.DateTime _Ngay_Dat;
		
		private int _Hinh_Thuc_Thanh_Toan;
		
		private string _Bang_Chung_Thanh_Toan;
		
		private int _Tinh_Trang;
		
		private string _Ma_Khach_Hang;
		
		private EntitySet<CHI_TIET_CHUYEN_HANG> _CHI_TIET_CHUYEN_HANGs;
		
		private EntitySet<CHI_TIET_DON_HANG> _CHI_TIET_DON_HANGs;
		
		private EntityRef<USER> _USER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Don_HangChanging(string value);
    partial void OnMa_Don_HangChanged();
    partial void OnMa_Chi_Tiet_DHChanging(string value);
    partial void OnMa_Chi_Tiet_DHChanged();
    partial void OnNgay_DatChanging(System.DateTime value);
    partial void OnNgay_DatChanged();
    partial void OnHinh_Thuc_Thanh_ToanChanging(int value);
    partial void OnHinh_Thuc_Thanh_ToanChanged();
    partial void OnBang_Chung_Thanh_ToanChanging(string value);
    partial void OnBang_Chung_Thanh_ToanChanged();
    partial void OnTinh_TrangChanging(int value);
    partial void OnTinh_TrangChanged();
    partial void OnMa_Khach_HangChanging(string value);
    partial void OnMa_Khach_HangChanged();
    #endregion
		
		public DON_HANG()
		{
			this._CHI_TIET_CHUYEN_HANGs = new EntitySet<CHI_TIET_CHUYEN_HANG>(new Action<CHI_TIET_CHUYEN_HANG>(this.attach_CHI_TIET_CHUYEN_HANGs), new Action<CHI_TIET_CHUYEN_HANG>(this.detach_CHI_TIET_CHUYEN_HANGs));
			this._CHI_TIET_DON_HANGs = new EntitySet<CHI_TIET_DON_HANG>(new Action<CHI_TIET_DON_HANG>(this.attach_CHI_TIET_DON_HANGs), new Action<CHI_TIET_DON_HANG>(this.detach_CHI_TIET_DON_HANGs));
			this._USER = default(EntityRef<USER>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Don_Hang", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Don_Hang
		{
			get
			{
				return this._Ma_Don_Hang;
			}
			set
			{
				if ((this._Ma_Don_Hang != value))
				{
					this.OnMa_Don_HangChanging(value);
					this.SendPropertyChanging();
					this._Ma_Don_Hang = value;
					this.SendPropertyChanged("Ma_Don_Hang");
					this.OnMa_Don_HangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Chi_Tiet_DH", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Ma_Chi_Tiet_DH
		{
			get
			{
				return this._Ma_Chi_Tiet_DH;
			}
			set
			{
				if ((this._Ma_Chi_Tiet_DH != value))
				{
					this.OnMa_Chi_Tiet_DHChanging(value);
					this.SendPropertyChanging();
					this._Ma_Chi_Tiet_DH = value;
					this.SendPropertyChanged("Ma_Chi_Tiet_DH");
					this.OnMa_Chi_Tiet_DHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Dat", DbType="Date NOT NULL")]
		public System.DateTime Ngay_Dat
		{
			get
			{
				return this._Ngay_Dat;
			}
			set
			{
				if ((this._Ngay_Dat != value))
				{
					this.OnNgay_DatChanging(value);
					this.SendPropertyChanging();
					this._Ngay_Dat = value;
					this.SendPropertyChanged("Ngay_Dat");
					this.OnNgay_DatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh_Thuc_Thanh_Toan", DbType="Int NOT NULL")]
		public int Hinh_Thuc_Thanh_Toan
		{
			get
			{
				return this._Hinh_Thuc_Thanh_Toan;
			}
			set
			{
				if ((this._Hinh_Thuc_Thanh_Toan != value))
				{
					this.OnHinh_Thuc_Thanh_ToanChanging(value);
					this.SendPropertyChanging();
					this._Hinh_Thuc_Thanh_Toan = value;
					this.SendPropertyChanged("Hinh_Thuc_Thanh_Toan");
					this.OnHinh_Thuc_Thanh_ToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bang_Chung_Thanh_Toan", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Bang_Chung_Thanh_Toan
		{
			get
			{
				return this._Bang_Chung_Thanh_Toan;
			}
			set
			{
				if ((this._Bang_Chung_Thanh_Toan != value))
				{
					this.OnBang_Chung_Thanh_ToanChanging(value);
					this.SendPropertyChanging();
					this._Bang_Chung_Thanh_Toan = value;
					this.SendPropertyChanged("Bang_Chung_Thanh_Toan");
					this.OnBang_Chung_Thanh_ToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinh_Trang", DbType="Int NOT NULL")]
		public int Tinh_Trang
		{
			get
			{
				return this._Tinh_Trang;
			}
			set
			{
				if ((this._Tinh_Trang != value))
				{
					this.OnTinh_TrangChanging(value);
					this.SendPropertyChanging();
					this._Tinh_Trang = value;
					this.SendPropertyChanged("Tinh_Trang");
					this.OnTinh_TrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Khach_Hang", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Ma_Khach_Hang
		{
			get
			{
				return this._Ma_Khach_Hang;
			}
			set
			{
				if ((this._Ma_Khach_Hang != value))
				{
					if (this._USER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_Khach_HangChanging(value);
					this.SendPropertyChanging();
					this._Ma_Khach_Hang = value;
					this.SendPropertyChanged("Ma_Khach_Hang");
					this.OnMa_Khach_HangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DON_HANG_CHI_TIET_CHUYEN_HANG", Storage="_CHI_TIET_CHUYEN_HANGs", ThisKey="Ma_Don_Hang", OtherKey="Ma_Don_Hang")]
		public EntitySet<CHI_TIET_CHUYEN_HANG> CHI_TIET_CHUYEN_HANGs
		{
			get
			{
				return this._CHI_TIET_CHUYEN_HANGs;
			}
			set
			{
				this._CHI_TIET_CHUYEN_HANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DON_HANG_CHI_TIET_DON_HANG", Storage="_CHI_TIET_DON_HANGs", ThisKey="Ma_Don_Hang", OtherKey="Ma_Don_Hang")]
		public EntitySet<CHI_TIET_DON_HANG> CHI_TIET_DON_HANGs
		{
			get
			{
				return this._CHI_TIET_DON_HANGs;
			}
			set
			{
				this._CHI_TIET_DON_HANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USER_DON_HANG", Storage="_USER", ThisKey="Ma_Khach_Hang", OtherKey="Ma_Khach_Hang", IsForeignKey=true)]
		public USER USER
		{
			get
			{
				return this._USER.Entity;
			}
			set
			{
				USER previousValue = this._USER.Entity;
				if (((previousValue != value) 
							|| (this._USER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USER.Entity = null;
						previousValue.DON_HANGs.Remove(this);
					}
					this._USER.Entity = value;
					if ((value != null))
					{
						value.DON_HANGs.Add(this);
						this._Ma_Khach_Hang = value.Ma_Khach_Hang;
					}
					else
					{
						this._Ma_Khach_Hang = default(string);
					}
					this.SendPropertyChanged("USER");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHI_TIET_CHUYEN_HANGs(CHI_TIET_CHUYEN_HANG entity)
		{
			this.SendPropertyChanging();
			entity.DON_HANG = this;
		}
		
		private void detach_CHI_TIET_CHUYEN_HANGs(CHI_TIET_CHUYEN_HANG entity)
		{
			this.SendPropertyChanging();
			entity.DON_HANG = null;
		}
		
		private void attach_CHI_TIET_DON_HANGs(CHI_TIET_DON_HANG entity)
		{
			this.SendPropertyChanging();
			entity.DON_HANG = this;
		}
		
		private void detach_CHI_TIET_DON_HANGs(CHI_TIET_DON_HANG entity)
		{
			this.SendPropertyChanging();
			entity.DON_HANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAI_TRAI_CAY")]
	public partial class LOAI_TRAI_CAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Loai_Trai_Cay;
		
		private string _Ten_Loai_Trai_Cay;
		
		private EntitySet<TRAI_CAY> _TRAI_CAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Loai_Trai_CayChanging(string value);
    partial void OnMa_Loai_Trai_CayChanged();
    partial void OnTen_Loai_Trai_CayChanging(string value);
    partial void OnTen_Loai_Trai_CayChanged();
    #endregion
		
		public LOAI_TRAI_CAY()
		{
			this._TRAI_CAYs = new EntitySet<TRAI_CAY>(new Action<TRAI_CAY>(this.attach_TRAI_CAYs), new Action<TRAI_CAY>(this.detach_TRAI_CAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Loai_Trai_Cay", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Loai_Trai_Cay
		{
			get
			{
				return this._Ma_Loai_Trai_Cay;
			}
			set
			{
				if ((this._Ma_Loai_Trai_Cay != value))
				{
					this.OnMa_Loai_Trai_CayChanging(value);
					this.SendPropertyChanging();
					this._Ma_Loai_Trai_Cay = value;
					this.SendPropertyChanged("Ma_Loai_Trai_Cay");
					this.OnMa_Loai_Trai_CayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Loai_Trai_Cay", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Ten_Loai_Trai_Cay
		{
			get
			{
				return this._Ten_Loai_Trai_Cay;
			}
			set
			{
				if ((this._Ten_Loai_Trai_Cay != value))
				{
					this.OnTen_Loai_Trai_CayChanging(value);
					this.SendPropertyChanging();
					this._Ten_Loai_Trai_Cay = value;
					this.SendPropertyChanged("Ten_Loai_Trai_Cay");
					this.OnTen_Loai_Trai_CayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_TRAI_CAY_TRAI_CAY", Storage="_TRAI_CAYs", ThisKey="Ma_Loai_Trai_Cay", OtherKey="Loai_ID")]
		public EntitySet<TRAI_CAY> TRAI_CAYs
		{
			get
			{
				return this._TRAI_CAYs;
			}
			set
			{
				this._TRAI_CAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TRAI_CAYs(TRAI_CAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAI_TRAI_CAY = this;
		}
		
		private void detach_TRAI_CAYs(TRAI_CAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAI_TRAI_CAY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOG_NHAP")]
	public partial class LOG_NHAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Auto_ID;
		
		private string _Ma_Trai_Cay;
		
		private System.DateTime _Thoi_Gian;
		
		private int _Tong_Tien;
		
		private int _So_Luong_Nhap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAuto_IDChanging(string value);
    partial void OnAuto_IDChanged();
    partial void OnMa_Trai_CayChanging(string value);
    partial void OnMa_Trai_CayChanged();
    partial void OnThoi_GianChanging(System.DateTime value);
    partial void OnThoi_GianChanged();
    partial void OnTong_TienChanging(int value);
    partial void OnTong_TienChanged();
    partial void OnSo_Luong_NhapChanging(int value);
    partial void OnSo_Luong_NhapChanged();
    #endregion
		
		public LOG_NHAP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auto_ID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Auto_ID
		{
			get
			{
				return this._Auto_ID;
			}
			set
			{
				if ((this._Auto_ID != value))
				{
					this.OnAuto_IDChanging(value);
					this.SendPropertyChanging();
					this._Auto_ID = value;
					this.SendPropertyChanged("Auto_ID");
					this.OnAuto_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Trai_Cay", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Ma_Trai_Cay
		{
			get
			{
				return this._Ma_Trai_Cay;
			}
			set
			{
				if ((this._Ma_Trai_Cay != value))
				{
					this.OnMa_Trai_CayChanging(value);
					this.SendPropertyChanging();
					this._Ma_Trai_Cay = value;
					this.SendPropertyChanged("Ma_Trai_Cay");
					this.OnMa_Trai_CayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoi_Gian", DbType="Date NOT NULL")]
		public System.DateTime Thoi_Gian
		{
			get
			{
				return this._Thoi_Gian;
			}
			set
			{
				if ((this._Thoi_Gian != value))
				{
					this.OnThoi_GianChanging(value);
					this.SendPropertyChanging();
					this._Thoi_Gian = value;
					this.SendPropertyChanged("Thoi_Gian");
					this.OnThoi_GianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tong_Tien", DbType="Int NOT NULL")]
		public int Tong_Tien
		{
			get
			{
				return this._Tong_Tien;
			}
			set
			{
				if ((this._Tong_Tien != value))
				{
					this.OnTong_TienChanging(value);
					this.SendPropertyChanging();
					this._Tong_Tien = value;
					this.SendPropertyChanged("Tong_Tien");
					this.OnTong_TienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Luong_Nhap", DbType="Int NOT NULL")]
		public int So_Luong_Nhap
		{
			get
			{
				return this._So_Luong_Nhap;
			}
			set
			{
				if ((this._So_Luong_Nhap != value))
				{
					this.OnSo_Luong_NhapChanging(value);
					this.SendPropertyChanging();
					this._So_Luong_Nhap = value;
					this.SendPropertyChanged("So_Luong_Nhap");
					this.OnSo_Luong_NhapChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOG_THANH_TOAN")]
	public partial class LOG_THANH_TOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Auto_ID;
		
		private System.DateTime _Thoi_Gian;
		
		private int _Tong_Tien;
		
		private string _Ma_Don_Hang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAuto_IDChanging(string value);
    partial void OnAuto_IDChanged();
    partial void OnThoi_GianChanging(System.DateTime value);
    partial void OnThoi_GianChanged();
    partial void OnTong_TienChanging(int value);
    partial void OnTong_TienChanged();
    partial void OnMa_Don_HangChanging(string value);
    partial void OnMa_Don_HangChanged();
    #endregion
		
		public LOG_THANH_TOAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auto_ID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Auto_ID
		{
			get
			{
				return this._Auto_ID;
			}
			set
			{
				if ((this._Auto_ID != value))
				{
					this.OnAuto_IDChanging(value);
					this.SendPropertyChanging();
					this._Auto_ID = value;
					this.SendPropertyChanged("Auto_ID");
					this.OnAuto_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoi_Gian", DbType="Date NOT NULL")]
		public System.DateTime Thoi_Gian
		{
			get
			{
				return this._Thoi_Gian;
			}
			set
			{
				if ((this._Thoi_Gian != value))
				{
					this.OnThoi_GianChanging(value);
					this.SendPropertyChanging();
					this._Thoi_Gian = value;
					this.SendPropertyChanged("Thoi_Gian");
					this.OnThoi_GianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tong_Tien", DbType="Int NOT NULL")]
		public int Tong_Tien
		{
			get
			{
				return this._Tong_Tien;
			}
			set
			{
				if ((this._Tong_Tien != value))
				{
					this.OnTong_TienChanging(value);
					this.SendPropertyChanging();
					this._Tong_Tien = value;
					this.SendPropertyChanged("Tong_Tien");
					this.OnTong_TienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Don_Hang", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Ma_Don_Hang
		{
			get
			{
				return this._Ma_Don_Hang;
			}
			set
			{
				if ((this._Ma_Don_Hang != value))
				{
					this.OnMa_Don_HangChanging(value);
					this.SendPropertyChanging();
					this._Ma_Don_Hang = value;
					this.SendPropertyChanged("Ma_Don_Hang");
					this.OnMa_Don_HangChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRAI_CAY")]
	public partial class TRAI_CAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Trai_Cay;
		
		private string _Ten_Trai_Cay;
		
		private int _So_Luong;
		
		private int _Don_Gia;
		
		private string _Don_Vi_Tinh;
		
		private string _Xuat_Xu;
		
		private string _Mo_Ta;
		
		private string _Loai_ID;
		
		private EntitySet<CHI_TIET_DON_HANG> _CHI_TIET_DON_HANGs;
		
		private EntitySet<CHI_TIET_TRAI_CAY> _CHI_TIET_TRAI_CAYs;
		
		private EntityRef<LOAI_TRAI_CAY> _LOAI_TRAI_CAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Trai_CayChanging(string value);
    partial void OnMa_Trai_CayChanged();
    partial void OnTen_Trai_CayChanging(string value);
    partial void OnTen_Trai_CayChanged();
    partial void OnSo_LuongChanging(int value);
    partial void OnSo_LuongChanged();
    partial void OnDon_GiaChanging(int value);
    partial void OnDon_GiaChanged();
    partial void OnDon_Vi_TinhChanging(string value);
    partial void OnDon_Vi_TinhChanged();
    partial void OnXuat_XuChanging(string value);
    partial void OnXuat_XuChanged();
    partial void OnMo_TaChanging(string value);
    partial void OnMo_TaChanged();
    partial void OnLoai_IDChanging(string value);
    partial void OnLoai_IDChanged();
    #endregion
		
		public TRAI_CAY()
		{
			this._CHI_TIET_DON_HANGs = new EntitySet<CHI_TIET_DON_HANG>(new Action<CHI_TIET_DON_HANG>(this.attach_CHI_TIET_DON_HANGs), new Action<CHI_TIET_DON_HANG>(this.detach_CHI_TIET_DON_HANGs));
			this._CHI_TIET_TRAI_CAYs = new EntitySet<CHI_TIET_TRAI_CAY>(new Action<CHI_TIET_TRAI_CAY>(this.attach_CHI_TIET_TRAI_CAYs), new Action<CHI_TIET_TRAI_CAY>(this.detach_CHI_TIET_TRAI_CAYs));
			this._LOAI_TRAI_CAY = default(EntityRef<LOAI_TRAI_CAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Trai_Cay", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Trai_Cay
		{
			get
			{
				return this._Ma_Trai_Cay;
			}
			set
			{
				if ((this._Ma_Trai_Cay != value))
				{
					this.OnMa_Trai_CayChanging(value);
					this.SendPropertyChanging();
					this._Ma_Trai_Cay = value;
					this.SendPropertyChanged("Ma_Trai_Cay");
					this.OnMa_Trai_CayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Trai_Cay", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Ten_Trai_Cay
		{
			get
			{
				return this._Ten_Trai_Cay;
			}
			set
			{
				if ((this._Ten_Trai_Cay != value))
				{
					this.OnTen_Trai_CayChanging(value);
					this.SendPropertyChanging();
					this._Ten_Trai_Cay = value;
					this.SendPropertyChanged("Ten_Trai_Cay");
					this.OnTen_Trai_CayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Luong", DbType="Int NOT NULL")]
		public int So_Luong
		{
			get
			{
				return this._So_Luong;
			}
			set
			{
				if ((this._So_Luong != value))
				{
					this.OnSo_LuongChanging(value);
					this.SendPropertyChanging();
					this._So_Luong = value;
					this.SendPropertyChanged("So_Luong");
					this.OnSo_LuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Don_Gia", DbType="Int NOT NULL")]
		public int Don_Gia
		{
			get
			{
				return this._Don_Gia;
			}
			set
			{
				if ((this._Don_Gia != value))
				{
					this.OnDon_GiaChanging(value);
					this.SendPropertyChanging();
					this._Don_Gia = value;
					this.SendPropertyChanged("Don_Gia");
					this.OnDon_GiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Don_Vi_Tinh", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Don_Vi_Tinh
		{
			get
			{
				return this._Don_Vi_Tinh;
			}
			set
			{
				if ((this._Don_Vi_Tinh != value))
				{
					this.OnDon_Vi_TinhChanging(value);
					this.SendPropertyChanging();
					this._Don_Vi_Tinh = value;
					this.SendPropertyChanged("Don_Vi_Tinh");
					this.OnDon_Vi_TinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Xuat_Xu", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Xuat_Xu
		{
			get
			{
				return this._Xuat_Xu;
			}
			set
			{
				if ((this._Xuat_Xu != value))
				{
					this.OnXuat_XuChanging(value);
					this.SendPropertyChanging();
					this._Xuat_Xu = value;
					this.SendPropertyChanged("Xuat_Xu");
					this.OnXuat_XuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mo_Ta", DbType="VarChar(5000) NOT NULL", CanBeNull=false)]
		public string Mo_Ta
		{
			get
			{
				return this._Mo_Ta;
			}
			set
			{
				if ((this._Mo_Ta != value))
				{
					this.OnMo_TaChanging(value);
					this.SendPropertyChanging();
					this._Mo_Ta = value;
					this.SendPropertyChanged("Mo_Ta");
					this.OnMo_TaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai_ID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Loai_ID
		{
			get
			{
				return this._Loai_ID;
			}
			set
			{
				if ((this._Loai_ID != value))
				{
					if (this._LOAI_TRAI_CAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoai_IDChanging(value);
					this.SendPropertyChanging();
					this._Loai_ID = value;
					this.SendPropertyChanged("Loai_ID");
					this.OnLoai_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAI_CAY_CHI_TIET_DON_HANG", Storage="_CHI_TIET_DON_HANGs", ThisKey="Ma_Trai_Cay", OtherKey="Ma_Trai_Cay")]
		public EntitySet<CHI_TIET_DON_HANG> CHI_TIET_DON_HANGs
		{
			get
			{
				return this._CHI_TIET_DON_HANGs;
			}
			set
			{
				this._CHI_TIET_DON_HANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAI_CAY_CHI_TIET_TRAI_CAY", Storage="_CHI_TIET_TRAI_CAYs", ThisKey="Ma_Trai_Cay", OtherKey="Ma_Trai_Cay")]
		public EntitySet<CHI_TIET_TRAI_CAY> CHI_TIET_TRAI_CAYs
		{
			get
			{
				return this._CHI_TIET_TRAI_CAYs;
			}
			set
			{
				this._CHI_TIET_TRAI_CAYs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_TRAI_CAY_TRAI_CAY", Storage="_LOAI_TRAI_CAY", ThisKey="Loai_ID", OtherKey="Ma_Loai_Trai_Cay", IsForeignKey=true)]
		public LOAI_TRAI_CAY LOAI_TRAI_CAY
		{
			get
			{
				return this._LOAI_TRAI_CAY.Entity;
			}
			set
			{
				LOAI_TRAI_CAY previousValue = this._LOAI_TRAI_CAY.Entity;
				if (((previousValue != value) 
							|| (this._LOAI_TRAI_CAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAI_TRAI_CAY.Entity = null;
						previousValue.TRAI_CAYs.Remove(this);
					}
					this._LOAI_TRAI_CAY.Entity = value;
					if ((value != null))
					{
						value.TRAI_CAYs.Add(this);
						this._Loai_ID = value.Ma_Loai_Trai_Cay;
					}
					else
					{
						this._Loai_ID = default(string);
					}
					this.SendPropertyChanged("LOAI_TRAI_CAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHI_TIET_DON_HANGs(CHI_TIET_DON_HANG entity)
		{
			this.SendPropertyChanging();
			entity.TRAI_CAY = this;
		}
		
		private void detach_CHI_TIET_DON_HANGs(CHI_TIET_DON_HANG entity)
		{
			this.SendPropertyChanging();
			entity.TRAI_CAY = null;
		}
		
		private void attach_CHI_TIET_TRAI_CAYs(CHI_TIET_TRAI_CAY entity)
		{
			this.SendPropertyChanging();
			entity.TRAI_CAY = this;
		}
		
		private void detach_CHI_TIET_TRAI_CAYs(CHI_TIET_TRAI_CAY entity)
		{
			this.SendPropertyChanging();
			entity.TRAI_CAY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USERS")]
	public partial class USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Khach_Hang;
		
		private string _Ten_Dang_Nhap;
		
		private string _Mat_Khau;
		
		private string _Ho_Ten;
		
		private string _So_Dien_Thoai;
		
		private string _Dia_Chi;
		
		private EntitySet<DON_HANG> _DON_HANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Khach_HangChanging(string value);
    partial void OnMa_Khach_HangChanged();
    partial void OnTen_Dang_NhapChanging(string value);
    partial void OnTen_Dang_NhapChanged();
    partial void OnMat_KhauChanging(string value);
    partial void OnMat_KhauChanged();
    partial void OnHo_TenChanging(string value);
    partial void OnHo_TenChanged();
    partial void OnSo_Dien_ThoaiChanging(string value);
    partial void OnSo_Dien_ThoaiChanged();
    partial void OnDia_ChiChanging(string value);
    partial void OnDia_ChiChanged();
    #endregion
		
		public USER()
		{
			this._DON_HANGs = new EntitySet<DON_HANG>(new Action<DON_HANG>(this.attach_DON_HANGs), new Action<DON_HANG>(this.detach_DON_HANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Khach_Hang", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Khach_Hang
		{
			get
			{
				return this._Ma_Khach_Hang;
			}
			set
			{
				if ((this._Ma_Khach_Hang != value))
				{
					this.OnMa_Khach_HangChanging(value);
					this.SendPropertyChanging();
					this._Ma_Khach_Hang = value;
					this.SendPropertyChanged("Ma_Khach_Hang");
					this.OnMa_Khach_HangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Dang_Nhap", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Ten_Dang_Nhap
		{
			get
			{
				return this._Ten_Dang_Nhap;
			}
			set
			{
				if ((this._Ten_Dang_Nhap != value))
				{
					this.OnTen_Dang_NhapChanging(value);
					this.SendPropertyChanging();
					this._Ten_Dang_Nhap = value;
					this.SendPropertyChanged("Ten_Dang_Nhap");
					this.OnTen_Dang_NhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mat_Khau", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Mat_Khau
		{
			get
			{
				return this._Mat_Khau;
			}
			set
			{
				if ((this._Mat_Khau != value))
				{
					this.OnMat_KhauChanging(value);
					this.SendPropertyChanging();
					this._Mat_Khau = value;
					this.SendPropertyChanged("Mat_Khau");
					this.OnMat_KhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ho_Ten", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Ho_Ten
		{
			get
			{
				return this._Ho_Ten;
			}
			set
			{
				if ((this._Ho_Ten != value))
				{
					this.OnHo_TenChanging(value);
					this.SendPropertyChanging();
					this._Ho_Ten = value;
					this.SendPropertyChanged("Ho_Ten");
					this.OnHo_TenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Dien_Thoai", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string So_Dien_Thoai
		{
			get
			{
				return this._So_Dien_Thoai;
			}
			set
			{
				if ((this._So_Dien_Thoai != value))
				{
					this.OnSo_Dien_ThoaiChanging(value);
					this.SendPropertyChanging();
					this._So_Dien_Thoai = value;
					this.SendPropertyChanged("So_Dien_Thoai");
					this.OnSo_Dien_ThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dia_Chi", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Dia_Chi
		{
			get
			{
				return this._Dia_Chi;
			}
			set
			{
				if ((this._Dia_Chi != value))
				{
					this.OnDia_ChiChanging(value);
					this.SendPropertyChanging();
					this._Dia_Chi = value;
					this.SendPropertyChanged("Dia_Chi");
					this.OnDia_ChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USER_DON_HANG", Storage="_DON_HANGs", ThisKey="Ma_Khach_Hang", OtherKey="Ma_Khach_Hang")]
		public EntitySet<DON_HANG> DON_HANGs
		{
			get
			{
				return this._DON_HANGs;
			}
			set
			{
				this._DON_HANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DON_HANGs(DON_HANG entity)
		{
			this.SendPropertyChanging();
			entity.USER = this;
		}
		
		private void detach_DON_HANGs(DON_HANG entity)
		{
			this.SendPropertyChanging();
			entity.USER = null;
		}
	}
}
#pragma warning restore 1591
